//! A final flush wrote a fresh completion seal over a capture its own `git add` had made stale
//! (review 2026-09-28, fifth pass, #2): the user's clean filter for one path wrote another path
//! git had already indexed, after every writer was stopped. The report said `changed`, but the
//! seal was on the chain, and a lost answer let it stand for a save of bytes no capture held.
//! No filter of the user's runs in a capture's git now: the disk holds still, the flush says
//! complete, and the sealed head restores exactly the disk.
//!
//! One test in its own binary on purpose: the sweep takes every descendant of the process it
//! runs in, as the daemon's does, and other tests' processes would be its descendants too.

mod support;

use support::{EXECUTOR, boot, final_flush, git, restore};

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn a_clean_filter_never_runs_under_a_final_flush() {
    let tmp = tempfile::tempdir().unwrap();
    let (boot, registrar) = boot(tmp.path(), |store| store);
    let ws = tmp.path().join("ws");
    std::fs::write(ws.join(".gitattributes"), b"z-trigger filter=mutator\n").unwrap();
    std::fs::write(ws.join("a-victim"), b"before filter\n").unwrap();
    std::fs::write(ws.join("z-trigger"), b"trigger\n").unwrap();
    git(
        &ws,
        &[
            "config",
            "filter.mutator.clean",
            "printf 'unique work generated by filter\\n' > a-victim; cat",
        ],
    );

    let report = final_flush(&ws, boot).await;
    assert_eq!(
        std::fs::read(ws.join("a-victim")).unwrap(),
        b"before filter\n",
        "the user's filter ran in a capture"
    );
    assert!(report.complete, "{report:?}");
    let seals = registrar.seals();
    assert!(
        seals.iter().any(|(_, seal)| seal.executor == EXECUTOR),
        "{seals:?}"
    );
    let fresh = restore(tmp.path(), &registrar, "fresh");
    for name in ["a-victim", "z-trigger", ".gitattributes"] {
        assert_eq!(
            std::fs::read(fresh.join(name)).unwrap(),
            std::fs::read(ws.join(name)).unwrap(),
            "{name}: the sealed head is the disk"
        );
    }
}
