//! Typed commands, events, identifiers, versions, and error codes for the sealantd control protocol.
//!
//! This crate is the single schema source of truth for the daemon's local control API. It is
//! deliberately lightweight (no async runtime, no I/O) so it can be consumed by the daemon, by
//! integration tooling, by tests, and by TypeScript schema generation.
//!
//! Wire model: every message is a single length-prefixed JSON frame (see [`frame`]). Clients send
//! [`ClientMessage`] frames; the daemon replies with [`ServerMessage`] frames that are either a
//! [`ControlResponse`] (exactly one per request) or an asynchronous telemetry [`EventEnvelope`].
//! Arbitrary process/terminal bytes are never assumed to be UTF-8: they travel as base64
//! ([`Base64Bytes`]) with an explicit original byte count.
#![cfg_attr(not(test), deny(clippy::unwrap_used, clippy::expect_used))]
#![forbid(unsafe_code)]

pub mod bytes;
pub mod command;
pub mod error;
pub mod event;
pub mod frame;
pub mod ids;
pub mod message;

pub use bytes::Base64Bytes;
pub use command::*;
pub use error::{ControlError, ControlErrorCode};
pub use event::*;
pub use frame::{DEFAULT_MAX_FRAME_BYTES, LENGTH_PREFIX_BYTES, MIN_MAX_FRAME_BYTES};
pub use ids::*;
pub use message::*;

/// Current wire schema version. Bumped on any breaking change to the framed JSON contract.
pub const SCHEMA_VERSION: u32 = 1;

/// Produce the JSON Schema bundle for the protocol, used to generate/validate TypeScript types.
///
/// The bundle covers both directions of the wire: `client` (what the SDK sends) and `server`
/// (what the daemon emits). Generated by `cargo run -p sealant-protocol --example dump-schema`.
#[must_use]
pub fn json_schema() -> serde_json::Value {
    let client = schemars::schema_for!(ClientMessage);
    let server = schemars::schema_for!(ServerMessage);
    serde_json::json!({
        "schemaVersion": SCHEMA_VERSION,
        "title": "sealantd-control-protocol",
        "client": client,
        "server": server,
    })
}
